title: Journal
description: Thoughts and things from Katie Sylor-Miller

remote_theme: chesterhow/tale

paginate:     5

# Author
author:
  name:         Katie Sylor-Miller
  url:          http://sylormiller.com

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
